# check=skip=SecretsUsedInArgOrEnv
FROM python:3.1-slim

ARG SERVICE_API_KEY
ENV SERVICE_API_KEY=${SERVICE_API_KEY:-}

WORKDIR /app
COPY requirements.txt .
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8004

# default command is web; in docker-compose we can override for worker
CMD ["uvicorn", "web:app", "--host", "0.0.0.0", "--port", "8004"]
