
name = "mistllc-frontend"
compatibility_date = "2025-08-29"
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "KV"
id = "1234567890abcdef1234567890abcdef"

[[d1_databases]]
binding = "DB"
database_name = "mistllc_db"
database_id = "8a00ac76-0737-4110-86e1-1c89e06f2421"

[vars]
API_KEY = "https://mistllc.org/api/*"