# --- Base ---
FROM node:24-alpine AS base
WORKDIR /app
COPY package*.json ./

# --- Dev ---
FROM base AS dev
RUN npm ci
COPY . .
EXPOSE 3000
CMD ["npm", "run", "dev"]

# --- Build ---
FROM base AS build
RUN npm ci
COPY . .
RUN npm run build

# --- Prod ---
FROM node:24-alpine AS prod
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/dist ./dist
COPY package*.json ./
RUN npm ci --omit=dev
EXPOSE 3000
CMD ["node", "dist/server.js"]
