name: Lint & Format Check

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . --ext .ts,.tsx,.js,.jsx

      - name: Run Prettier (check only)
        run: npx prettier --check .
